# Generated by Django 5.2.2 on 2025-06-12 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_card_is_default_alter_card_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO 4217 currency code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('flag_emoji', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(default='RUB', help_text='The base currency for the rate (e.g., RUB)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, help_text='Rate of the currency against the base currency', max_digits=20)),
                ('timestamp', models.DateTimeField(help_text='The timestamp of the recorded rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.currency')),
            ],
            options={
                'verbose_name': 'Currency History',
                'verbose_name_plural': 'Currency History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency', 'timestamp'], name='api_currenc_currenc_5d2c95_idx')],
            },
        ),
    ]
