# Generated by Django 5.0.7 on 2024-07-26 13:42

from django.db import migrations

CURRENCIES = [
    {"code": "RUB", "name": "Russian Ruble", "flag_emoji": "🇷🇺"},
    {"code": "USD", "name": "United States Dollar", "flag_emoji": "🇺🇸"},
    {"code": "EUR", "name": "Euro", "flag_emoji": "🇪🇺"},
    {"code": "CNY", "name": "Chinese Yuan", "flag_emoji": "🇨🇳"},
    {"code": "GBP", "name": "British Pound Sterling", "flag_emoji": "🇬🇧"},
    {"code": "JPY", "name": "Japanese Yen", "flag_emoji": "🇯🇵"},
    {"code": "KZT", "name": "Kazakhstani Tenge", "flag_emoji": "🇰🇿"},
]

def seed_currencies(apps, schema_editor):
    Currency = apps.get_model('api', 'Currency')
    for currency_data in CURRENCIES:
        Currency.objects.get_or_create(
            code=currency_data['code'],
            defaults={'name': currency_data['name'], 'flag_emoji': currency_data['flag_emoji']}
        )

def unseed_currencies(apps, schema_editor):
    Currency = apps.get_model('api', 'Currency')
    currency_codes = [c['code'] for c in CURRENCIES]
    Currency.objects.filter(code__in=currency_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_currency_currencyhistory'),
    ]

    operations = [
        migrations.RunPython(seed_currencies, reverse_code=unseed_currencies),
    ]
