# Generated by Django 5.2.3 on 2025-06-12 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_forumpost_forumcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('services', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
            },
        ),
    ]
