# Generated by Django 4.2.13 on 2025-06-12 10:29

from django.db import migrations

TERMINALS_DATA = [
    {"name": "Терминал №8", "address": "ул. Центральная, 10, Артем", "latitude": "43.3890", "longitude": "132.1900", "is_active": True, "services": {"payment": True}},
    {"name": "Терминал №3", "address": "ул. Пушкинская, 20, Владивосток", "latitude": "43.1189", "longitude": "131.8812", "is_active": True, "services": {"cash_in": True, "cash_out": True, "payment": True}},
    {"name": "Терминал №1", "address": "ул. Светланская, 1, Владивосток", "latitude": "43.1168", "longitude": "131.8875", "is_active": True, "services": {"cash_in": True, "cash_out": True, "payment": True}},
    {"name": "Терминал №11", "address": "ул. Гагарина, 12, Артем", "latitude": "43.3920", "longitude": "132.1960", "is_active": True, "services": {"cash_in": True, "cash_out": True, "payment": True}},
    {"name": "Терминал №5", "address": "ул. Тигровая, 10, Владивосток", "latitude": "43.1125", "longitude": "131.8860", "is_active": True, "services": {"cash_in": True, "cash_out": True, "payment": True}},
    {"name": "Терминал №10", "address": "ул. Советская, 7, Артем", "latitude": "43.3915", "longitude": "132.1950", "is_active": True, "services": {"payment": True}},
    {"name": "Терминал №4", "address": "ул. Адмирала Фокина, 8, Владивосток", "latitude": "43.1150", "longitude": "131.8850", "is_active": True, "services": {"payment": True}},
    {"name": "Терминал №7", "address": "ул. Лазо, 3, Артем", "latitude": "43.3870", "longitude": "132.1870", "is_active": True, "services": {"cash_in": True, "cash_out": True, "payment": True}},
    {"name": "Терминал №9", "address": "ул. Пушкина, 5, Артем", "latitude": "43.3905", "longitude": "132.1935", "is_active": True, "services": {"cash_in": True, "cash_out": True, "payment": True}},
    {"name": "Терминал №2", "address": "ул. Алеутская, 15, Владивосток", "latitude": "43.1175", "longitude": "131.8831", "is_active": True, "services": {"payment": True}},
    {"name": "Терминал №6", "address": "пр. Красного Знамени, 25, Владивосток", "latitude": "43.1210", "longitude": "131.8899", "is_active": True, "services": {"payment": True}},
]

def populate_terminals(apps, schema_editor):
    Terminal = apps.get_model('api', 'Terminal')
    for terminal_data in TERMINALS_DATA:
        Terminal.objects.get_or_create(
            name=terminal_data["name"],
            defaults=terminal_data
        )

def delete_terminals(apps, schema_editor):
    Terminal = apps.get_model('api', 'Terminal')
    names = [t['name'] for t in TERMINALS_DATA]
    Terminal.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_terminal'),
    ]

    operations = [
        migrations.RunPython(populate_terminals, reverse_code=delete_terminals),
    ]
