# Generated by Django 5.2.3 on 2025-06-13 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_aichat_aichatmessage_predictionpost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Like',
                'verbose_name_plural': 'Forum Likes',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
