# Generated by Django 5.2.3 on 2025-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_card_card_image_card_is_blocked_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_expiry',
            field=models.DateField(blank=True, help_text='Card expiry (alias for card_expiry_date)', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_issue_date_alias',
            field=models.DateField(blank=True, help_text='Card issue date (alias)', null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateField(blank=True, help_text='Deposit date (alias for start_date)', null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total interest earned', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original loan amount (alias for total_amount)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateField(blank=True, help_text='Loan date (alias for issue_date)', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='late_payments',
            field=models.IntegerField(default=0, help_text='Number of late payments'),
        ),
        migrations.AddField(
            model_name='loan',
            name='next_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Next payment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mortgage amount (alias)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='central_bank_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Central bank rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Property cost (alias)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='date',
            field=models.DateField(blank=True, help_text='Mortgage date (alias for issue_date)', null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='first_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First payment (alias)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='late_payments',
            field=models.IntegerField(default=0, help_text='Number of late payments'),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='overpayment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total overpayment amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate (alias)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total payment amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='years',
            field=models.IntegerField(blank=True, help_text='Term in years (alias for term_years)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Transaction date (alias for timestamp)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(blank=True, help_text='Transaction type (alias for transaction_type)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='User main balance', max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='card_cvv',
            field=models.CharField(blank=True, help_text='Primary card CVV', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry',
            field=models.DateField(blank=True, help_text='Primary card expiry', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_issue_date',
            field=models.DateField(blank=True, help_text='Primary card issue date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_name',
            field=models.CharField(blank=True, help_text='Primary card name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, help_text='Primary card number', max_length=19),
        ),
        migrations.AddField(
            model_name='user',
            name='gradient_end_hex',
            field=models.CharField(blank=True, help_text='Hex color for card gradient end', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='gradient_start_hex',
            field=models.CharField(blank=True, help_text='Hex color for card gradient start', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(default=True, help_text='Is user account active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False, help_text='Is user currently authenticated'),
        ),
        migrations.AddField(
            model_name='user',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Account issue date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, help_text='User status', max_length=50),
        ),
    ]
