# Generated by Django 5.2.3 on 2025-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_card_card_expiry_card_card_issue_date_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_issue_date_alias',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='first_payment',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='total_payment',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='years',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_issue_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gradient_end_hex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gradient_start_hex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total balance across all cards and deposits', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of next payment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='central_bank_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Central bank rate for calculations', max_digits=5),
        ),
    ]
