# Generated by Django 4.2.7 on 2025-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_card_card_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к транзакции', null=True),
        ),
    ]
